// Mirrors `src/mainview/runtime/externals.ts` (importing it would pull React DOM into the main process);
// a test keeps them in sync. `uai/<name>` are uai blocks, imported as `@/components/ui/uai/<name>` like their path.
const MODULE_EXPORTS = {
	avatar: ["Avatar", "AvatarImage", "AvatarFallback", "AvatarBadge", "AvatarGroup", "AvatarGroupCount"],
	badge: ["Badge", "badgeVariants"],
	button: ["Button", "buttonVariants"],
	card: ["Card", "CardHeader", "CardFooter", "CardTitle", "CardAction", "CardDescription", "CardContent"],
	collapsible: ["Collapsible", "CollapsibleTrigger", "CollapsibleContent"],
	dialog: [
		"Dialog",
		"DialogClose",
		"DialogContent",
		"DialogDescription",
		"DialogFooter",
		"DialogHeader",
		"DialogOverlay",
		"DialogPortal",
		"DialogTitle",
		"DialogTrigger",
	],
	"dropdown-menu": [
		"DropdownMenu",
		"DropdownMenuPortal",
		"DropdownMenuTrigger",
		"DropdownMenuContent",
		"DropdownMenuGroup",
		"DropdownMenuLabel",
		"DropdownMenuItem",
		"DropdownMenuCheckboxItem",
		"DropdownMenuRadioGroup",
		"DropdownMenuRadioItem",
		"DropdownMenuSeparator",
		"DropdownMenuShortcut",
		"DropdownMenuSub",
		"DropdownMenuSubTrigger",
		"DropdownMenuSubContent",
	],
	input: ["Input"],
	kbd: ["Kbd", "KbdGroup"],
	label: ["Label"],
	popover: [
		"Popover",
		"PopoverTrigger",
		"PopoverContent",
		"PopoverAnchor",
		"PopoverHeader",
		"PopoverTitle",
		"PopoverDescription",
	],
	progress: ["Progress"],
	"scroll-area": ["ScrollArea", "ScrollBar"],
	separator: ["Separator"],
	tabs: ["Tabs", "TabsList", "TabsTrigger", "TabsContent", "tabsListVariants"],
	textarea: ["Textarea"],
	toggle: ["Toggle", "toggleVariants"],
	"toggle-group": ["ToggleGroup", "ToggleGroupItem"],
	tooltip: ["Tooltip", "TooltipTrigger", "TooltipContent", "TooltipProvider"],
	"uai/form-error-summary": [
		"FormErrorSummary",
		"FormErrorSummaryTitle",
		"FormErrorSummaryList",
		"FormErrorSummaryLink",
	],
	"uai/form-field": [
		"FormField",
		"FormFieldLabel",
		"FormFieldInput",
		"FormFieldTextarea",
		"FormFieldDescription",
		"FormFieldError",
		"FormFieldCount",
	],
	"uai/message": [
		"Message",
		"MessageAvatar",
		"MessageBody",
		"MessageHeader",
		"MessageAuthor",
		"MessageTime",
		"MessageContent",
		"MessageActions",
		"MessageAction",
		"MessageCopy",
	],
	"uai/metric-card": [
		"MetricCard",
		"MetricCardLabel",
		"MetricCardValue",
		"MetricCardTrend",
		"MetricCardComparison",
		"MetricCardDescription",
		"MetricCardHeader",
	],
	"uai/prompt-composer": [
		"PromptComposer",
		"PromptComposerAdd",
		"PromptComposerAddItem",
		"PromptComposerFileItem",
		"PromptComposerInput",
		"PromptComposerActions",
		"PromptComposerModelSelect",
		"PromptComposerSubmit",
	],
	"uai/search-field": [
		"SearchField",
		"SearchFieldLabel",
		"SearchFieldControl",
		"SearchFieldInput",
		"SearchFieldClear",
		"SearchFieldMessage",
		"SearchFieldRecent",
		"SearchFieldRecentItem",
	],
	"uai/status-banner": [
		"StatusBanner",
		"StatusBannerIcon",
		"StatusBannerContent",
		"StatusBannerTitle",
		"StatusBannerDescription",
		"StatusBannerActions",
		"StatusBannerAction",
		"StatusBannerDismiss",
	],
	"uai/step-indicator": ["StepIndicator", "StepIndicatorStep", "StepIndicatorTitle", "StepIndicatorDescription"],
	"uai/thinking": ["Thinking", "ThinkingTrigger", "ThinkingContent", "ThinkingActivity"],
} satisfies Record<string, readonly string[]>;

export type UiModule = keyof typeof MODULE_EXPORTS;

export const UI_MODULES: Readonly<Record<UiModule, readonly string[]>> = MODULE_EXPORTS;

export function isUiModule(name: string): name is UiModule {
	return Object.hasOwn(UI_MODULES, name);
}
